### ISSUE TITLE
Add color code on place text cursor

### ISSUE THREAD

**Issue by zkainee** [flytegg/mcu-website#140]
When typing text in Color Text Generator, the color or font will be automatically placed at the end of the line. 

Recording; 
https://github.com/flytegg/mcu-website/assets/50738564/9cf6622d-a44e-4dcd-ba11-534a6a7ca167

**Comment by DanIsLit** [comment]
Hiya, thanks for the feedback.
This is expected behavior. If you selected them formatting options and it applied to the entire message then it would actually _limit_ the customizability of the util because a user might only want a select part of the message to be underlined, for example. 

Hope this helps!

**Comment by Nuckerr** [comment]
I think it would be more intuitive if it placed the format at the text cursor. Having it at the end makes it hard to go back and edit.

**Comment by DanIsLit** [comment]
Didn't think of that at all, fixed!
