### ISSUE TITLE
Minecraft server-icon.png maker

### ISSUE THREAD

**Issue by OneBiteAidan** [flytegg/mcu-website#144]
Add a utility that takes any image and crops and resizes it to be a 64x64 png image titled server-icon.

**Comment by stephendotgg** [comment]
Ok, will make.

**Comment by stephendotgg** [comment]
Here you go: https://mcutils.com/server-icon-converter

Only caveat: no cropping mechanism as of yet. Will just resize any inputted image to 64x64. So technically works perfect since nobody should be trying to make a server icon out of anything other than an already square icon, but may be a nice interactive feature for the future (#155).

Thanks for the suggestion, hope you find some use from it.
